import React, { useMemo, useRef, useState } from 'react';
import { Animated, Dimensions, Image, PanResponder, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFonts, DMSans_400Regular, DMSans_600SemiBold, DMSans_700Bold } from '@expo-google-fonts/dm-sans';
import { PlayfairDisplay_700Bold } from '@expo-google-fonts/playfair-display';
import { Ionicons } from '@expo/vector-icons';

const P = '#D72B78', BG = '#FFF9FC', INK = '#29212A', MUTED = '#80727D', LINE = '#F0DFE9', W = Dimensions.get('window').width;
const photo = id => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=82`;
// Stock portraits illustrate fictional DEMO profiles; never present them as real users.
const PEOPLE = [
 { id:1, name:'Maja', age:22, city:'Warszawa', photo:photo('photo-1534528741775-53994a69daeb'), about:'Uwielbiam małe kawiarnie i wielkie plany.', tags:['Kawa','Sztuka'], prompt:'Idealna sobota?', answer:'Śniadanie na mieście, a potem spontaniczny pociąg gdziekolwiek.' },
 { id:2, name:'Ola', age:21, city:'Kraków', photo:photo('photo-1524504388940-b1c1722653e1'), about:'Szukam ekipy na długie spacery.', tags:['Podróże','Kino'], prompt:'Dogadamy się, jeśli…', answer:'Lubisz rozmawiać godzinami i odkrywać nowe miejsca.' },
 { id:3, name:'Natalia', age:24, city:'Gdańsk', photo:photo('photo-1517841905240-472988babdf9'), about:'Weekend nad morzem? Wchodzę w to.', tags:['Fitness','Muzyka'], prompt:'Mój mały rytuał', answer:'Poranna kawa i spacer nad wodą.' },
 { id:4, name:'Julia', age:23, city:'Wrocław', photo:photo('photo-1531123897727-8f129e1688ce'), about:'Najlepsze historie zaczynają się spontanicznie.', tags:['Książki','Podróże'], prompt:'Chodźmy razem na…', answer:'Wystawę, koncert albo po prostu na miasto.' },
 { id:5, name:'Ania', age:22, city:'Poznań', photo:photo('photo-1529139574466-a303027c1d8b'), about:'Nowe miasto. Nowe znajomości.', tags:['Moda','Kawa'], prompt:'Trzy rzeczy, które lubię', answer:'Dobre rozmowy, zachody słońca i spontaniczne wycieczki.' },
 { id:6, name:'Zosia', age:23, city:'Łódź', photo:photo('photo-1544005313-94ddf0286df2'), about:'Szukam dziewczyn do wspólnych planów.', tags:['Fotografia','Muzyka'], prompt:'Zaproś mnie na…', answer:'Spacer z aparatem i coś dobrego do jedzenia.' }
];
const POSTS = [
 {id:1, by:'Maja', city:'Warszawa', text:'Kto idzie na kawę w weekend?', likes:12, image:PEOPLE[0].photo},
 {id:2, by:'Julia', city:'Wrocław', text:'Szukam dziewczyn na wspólny koncert.', likes:8, image:PEOPLE[3].photo},
 {id:3, by:'Natalia', city:'Gdańsk', text:'Spacer nad morzem w sobotę?', likes:18, image:PEOPLE[2].photo}
];
const GROUPS = [
 {id:1,name:'Coffee girls',city:'Warszawa',line:'Kawa i nowe znajomości',icon:'cafe-outline'},
 {id:2,name:'Girls club',city:'Kraków',line:'Spotkania w mieście',icon:'flower-outline'},
 {id:3,name:'Book club',city:'Gdańsk',line:'Książki i rozmowy',icon:'book-outline'},
 {id:4,name:'Weekend trips',city:'Wrocław',line:'Wspólne wypady',icon:'airplane-outline'}
];
const CHATS = [{id:1,name:'Maja',message:'Hej! Masz czas na kawę?',image:PEOPLE[0].photo},{id:2,name:'Girls club',message:'Widzimy się w sobotę!',image:PEOPLE[3].photo}];
const TABS = [
 {name:'Odkrywaj',icon:'heart-outline',active:'heart'},
 {name:'Społeczność',icon:'newspaper-outline',active:'newspaper'},
 {name:'Grupy',icon:'people-outline',active:'people'},
 {name:'Czaty',icon:'chatbubble-outline',active:'chatbubble'},
 {name:'Profil',icon:'person-outline',active:'person'}
];
const F = {regular:'DMSans_400Regular',semi:'DMSans_600SemiBold',bold:'DMSans_700Bold',display:'PlayfairDisplay_700Bold'};
function Txt({children,style,display=false,bold=false,...rest}) {return <Text {...rest} style={[{color:INK,fontFamily:display?F.display:bold?F.bold:F.regular},style]}>{children}</Text>}
function Btn({children,onPress,light=false}) {return <TouchableOpacity onPress={onPress} style={[s.btn,light&&s.btnLight]}><Txt bold style={{color:light?P:'#fff',fontSize:15}}>{children}</Txt></TouchableOpacity>}
function Heading({label,title}) {return <View style={{marginBottom:17}}><Txt bold style={s.eyebrow}>{label}</Txt><Txt display style={s.title}>{title}</Txt></View>}
function Avatar({uri,size=46}) {return <Image source={{uri}} style={{width:size,height:size,borderRadius:size/2,backgroundColor:LINE}}/>}
export default function App(){
 const [ready]=useFonts({DMSans_400Regular,DMSans_600SemiBold,DMSans_700Bold,PlayfairDisplay_700Bold});
 const [tab,setTab]=useState('Odkrywaj'),[city,setCity]=useState('Wszystkie'),[index,setIndex]=useState(0),[liked,setLiked]=useState([]),[joined,setJoined]=useState([]),[likedPosts,setLikedPosts]=useState([]),[posts,setPosts]=useState(POSTS),[draft,setDraft]=useState(''),[chat,setChat]=useState(null),[message,setMessage]=useState(''),[messages,setMessages]=useState([]),[notice,setNotice]=useState('');
 const drag=useRef(new Animated.ValueXY()).current;
 const shown=PEOPLE.filter(p=>city==='Wszystkie'||p.city===city),person=shown.length?shown[index%shown.length]:null;
 const swipe=dir=>Animated.timing(drag,{toValue:{x:dir*W,y:10},duration:190,useNativeDriver:true}).start(()=>{if(dir>0&&person)setLiked(v=>v.includes(person.id)?v:[...v,person.id]);setIndex(i=>i+1);drag.setValue({x:0,y:0})});
 const pan=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>18&&Math.abs(g.dx)>Math.abs(g.dy),onPanResponderMove:Animated.event([null,{dx:drag.x,dy:drag.y}],{useNativeDriver:false}),onPanResponderRelease:(_,g)=>Math.abs(g.dx)>95?swipe(g.dx>0?1:-1):Animated.spring(drag,{toValue:{x:0,y:0},useNativeDriver:true}).start()}),[person]);
 if(!ready)return <View style={{flex:1,backgroundColor:BG}}/>;
 const info=person?<ScrollView key={person.id} showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:36}}><Animated.View {...pan.panHandlers} style={[s.photoCard,{transform:[{translateX:drag.x},{translateY:drag.y},{rotate:drag.x.interpolate({inputRange:[-W,0,W],outputRange:['-10deg','0deg','10deg']})}]}]}><Image source={{uri:person.photo}} style={s.hero} resizeMode="cover"/><View style={s.photoLabel}><Txt bold style={{color:P,fontSize:11}}>PRZYKŁADOWY PROFIL</Txt></View></Animated.View><View style={s.personDetails}><Txt display style={{fontSize:36}}>{person.name}, {person.age}</Txt><Txt style={{fontSize:15,color:MUTED,marginTop:6}}>◉ {person.city}</Txt><Txt style={{fontSize:19,marginTop:18,lineHeight:27}}>{person.about}</Txt><View style={s.tagRow}>{person.tags.map(t=><View key={t} style={s.tag}><Txt bold style={{color:P}}>{t}</Txt></View>)}</View><View style={s.prompt}><Txt bold style={{color:P,fontSize:13}}>{person.prompt}</Txt><Txt display style={{fontSize:24,lineHeight:32,marginTop:9}}>{person.answer}</Txt></View><Btn onPress={()=>swipe(1)}>♡  Chcę ją poznać</Btn><Btn light onPress={()=>swipe(-1)}>Pomiń →</Btn></View></ScrollView>:<Txt>Brak profili w tym mieście.</Txt>;
 const discover=<View style={{flex:1}}><View style={s.pageHeader}><Heading label="MYGIRL / POLSKA" title="Poznaj się."/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{['Wszystkie','Warszawa','Kraków','Gdańsk','Wrocław','Poznań','Łódź'].map(c=><TouchableOpacity key={c} onPress={()=>{setCity(c);setIndex(0)}} style={[s.filter,city===c&&s.filterOn]}><Txt bold style={{fontSize:12,color:city===c?'#fff':P}}>{c}</Txt></TouchableOpacity>)}</ScrollView></View>{info}</View>;
 const community=<ScrollView contentContainerStyle={s.page}><Heading label="TWÓJ FEED" title="Społeczność."/><View style={s.compose}><TextInput placeholder="Co u Ciebie?" placeholderTextColor={MUTED} multiline value={draft} onChangeText={setDraft} style={{fontFamily:F.regular,fontSize:17,minHeight:44,color:INK,flex:1}}/><TouchableOpacity onPress={()=>{if(!draft.trim())return;setPosts(v=>[{id:Date.now(),by:'Ty',city:'Polska',text:draft.trim(),likes:0,image:null},...v]);setDraft('')}} style={s.send}><Ionicons name="arrow-up" color="#fff" size={20}/></TouchableOpacity></View>{posts.map(p=><View key={p.id} style={s.feed}><View style={{flexDirection:'row',alignItems:'center',gap:12}}>{p.image?<Avatar uri={p.image}/>:<View style={s.blankAvatar}><Ionicons name="person" color={P} size={21}/></View>}<View style={{flex:1}}><Txt bold style={{fontSize:17}}>{p.by}</Txt><Txt style={{color:MUTED,fontSize:12}}>{p.city} · demo</Txt></View></View><Txt style={{fontSize:19,lineHeight:26,marginTop:19}}>{p.text}</Txt><TouchableOpacity style={{marginTop:18,flexDirection:'row',alignItems:'center',gap:6}} onPress={()=>setLikedPosts(v=>v.includes(p.id)?v.filter(n=>n!==p.id):[...v,p.id])}><Ionicons name={likedPosts.includes(p.id)?'heart':'heart-outline'} color={P} size={20}/><Txt style={{color:MUTED}}>{p.likes+(likedPosts.includes(p.id)?1:0)}</Txt></TouchableOpacity></View>)}</ScrollView>;
 const groups=<ScrollView contentContainerStyle={s.page}><Heading label="TWOJE MIEJSCE" title="Grupy."/>{GROUPS.map(g=><View key={g.id} style={s.group}><View style={s.groupIcon}><Ionicons name={g.icon} size={26} color={P}/></View><View style={{flex:1}}><Txt bold style={{fontSize:19}}>{g.name}</Txt><Txt style={{fontSize:13,color:MUTED,marginTop:4}}>{g.city} · {g.line}</Txt></View><TouchableOpacity onPress={()=>setJoined(v=>v.includes(g.id)?v.filter(n=>n!==g.id):[...v,g.id])} style={s.join}><Ionicons name={joined.includes(g.id)?'checkmark':'add'} size={24} color={P}/></TouchableOpacity></View>)}<Txt style={s.demo}>Przykładowe grupy · bez serwera</Txt></ScrollView>;
 const chats=<View style={[s.page,{flex:1}]}><Heading label="ROZMOWY" title={chat?chat.name:'Czaty.'}/>{chat?<><TouchableOpacity onPress={()=>setChat(null)} style={{marginBottom:16}}><Txt bold style={{color:P}}>← Wszystkie czaty</Txt></TouchableOpacity><ScrollView style={{flex:1}}><View style={s.bubble}><Txt>Hej! Co u Ciebie?</Txt></View>{messages.filter(m=>m.id===chat.id).map((m,i)=><View key={i} style={[s.bubble,{alignSelf:'flex-end',backgroundColor:P}]}><Txt style={{color:'#fff'}}>{m.text}</Txt></View>)}</ScrollView><View style={s.compose}><TextInput value={message} onChangeText={setMessage} placeholder="Wiadomość…" style={{flex:1,fontFamily:F.regular,fontSize:16}}/><TouchableOpacity onPress={()=>{if(message.trim()){setMessages(v=>[...v,{id:chat.id,text:message.trim()}]);setMessage('')}}}><Ionicons name="send" size={24} color={P}/></TouchableOpacity></View></>:CHATS.map(c=><TouchableOpacity key={c.id} style={s.chat} onPress={()=>setChat(c)}><Avatar uri={c.image} size={56}/><View style={{flex:1}}><Txt bold style={{fontSize:19}}>{c.name}</Txt><Txt style={{color:MUTED,marginTop:5}}>{c.message}</Txt></View><Ionicons name="chevron-forward" color={MUTED} size={18}/></TouchableOpacity>)}<Txt style={s.demo}>Rozmowy demonstracyjne. Wiadomości nie są wysyłane do innych osób.</Txt></View>;
 const profile=<ScrollView contentContainerStyle={s.page}><Heading label="TWOJA PRZESTRZEŃ" title="Profil."/><View style={s.profile}><View style={s.blankAvatar}><Ionicons name="person-outline" color={P} size={25}/></View><Txt display style={{fontSize:32,marginTop:20}}>Twoje miejsce.</Txt><Txt style={{color:MUTED,marginTop:7}}>MyGirl · wersja demonstracyjna</Txt><View style={{flexDirection:'row',justifyContent:'space-around',marginTop:30}}>{[[liked.length,'Polubione'],[joined.length,'Grupy'],[posts.length-POSTS.length,'Posty']].map(([n,label])=><View key={label} style={{alignItems:'center'}}><Txt display style={{fontSize:32}}>{n}</Txt><Txt style={{color:MUTED,fontSize:12}}>{label}</Txt></View>)}</View></View><Btn light onPress={()=>setNotice('Edycja profilu wymaga podłączenia kont.')}>Edytuj profil</Btn><Txt style={s.demo}>Profile, zdjęcia i czaty są przykładowe.</Txt></ScrollView>;
 return <SafeAreaView style={{flex:1,backgroundColor:BG}}><StatusBar barStyle="dark-content" backgroundColor={BG}/><View style={{flex:1}}>{tab==='Odkrywaj'?discover:tab==='Społeczność'?community:tab==='Grupy'?groups:tab==='Czaty'?chats:profile}</View>{notice?<TouchableOpacity onPress={()=>setNotice('')} style={s.notice}><Txt style={{color:P}}>{notice} ×</Txt></TouchableOpacity>:null}<View style={s.nav}>{TABS.map(t=><TouchableOpacity key={t.name} accessibilityRole="tab" accessibilityLabel={t.name} accessibilityState={{selected:tab===t.name}} onPress={()=>{setTab(t.name);setNotice('')}} style={s.navItem}><View style={[s.navPill,tab===t.name&&{backgroundColor:'#FCE1ED'}]}><Ionicons name={tab===t.name?t.active:t.icon} size={22} color={tab===t.name?P:MUTED}/></View><Txt bold style={{fontSize:9,color:tab===t.name?P:MUTED}} numberOfLines={1}>{t.name}</Txt></TouchableOpacity>)}</View></SafeAreaView>
}
const s=StyleSheet.create({page:{padding:22,paddingBottom:38},pageHeader:{paddingHorizontal:22,paddingTop:22,paddingBottom:15},eyebrow:{fontSize:10,letterSpacing:2,color:P,marginBottom:9},title:{fontSize:35,lineHeight:43},filter:{paddingHorizontal:15,paddingVertical:10,borderWidth:1,borderColor:LINE,borderRadius:30,backgroundColor:'#fff'},filterOn:{backgroundColor:P,borderColor:P},photoCard:{marginHorizontal:22,borderRadius:23,overflow:'hidden',backgroundColor:'#F2E5EC'},hero:{width:'100%',height:Math.min(W*1.13,490),backgroundColor:'#F2E5EC'},photoLabel:{position:'absolute',top:15,left:15,backgroundColor:'#fff',paddingHorizontal:12,paddingVertical:8,borderRadius:22},personDetails:{padding:23},tagRow:{flexDirection:'row',gap:9,marginTop:19,flexWrap:'wrap'},tag:{paddingVertical:9,paddingHorizontal:15,backgroundColor:'#FCE7F0',borderRadius:22},prompt:{backgroundColor:'#fff',borderWidth:1,borderColor:LINE,padding:21,borderRadius:20,marginTop:26,marginBottom:18},btn:{backgroundColor:P,alignItems:'center',padding:17,borderRadius:17,marginTop:11},btnLight:{backgroundColor:'#FBE6EF'},compose:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#fff',borderWidth:1,borderColor:LINE,borderRadius:20,padding:15,marginBottom:22},send:{backgroundColor:P,width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'},feed:{backgroundColor:'#fff',borderRadius:23,borderColor:LINE,borderWidth:1,padding:19,marginBottom:15},blankAvatar:{height:46,width:46,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:'#FCE1ED'},group:{flexDirection:'row',gap:14,alignItems:'center',backgroundColor:'#fff',borderRadius:22,borderWidth:1,borderColor:LINE,padding:15,marginBottom:13},groupIcon:{width:55,height:55,borderRadius:17,backgroundColor:'#FCE1ED',alignItems:'center',justifyContent:'center'},join:{width:39,height:39,borderRadius:20,backgroundColor:BG,alignItems:'center',justifyContent:'center'},chat:{flexDirection:'row',gap:15,alignItems:'center',paddingVertical:17,borderBottomWidth:1,borderBottomColor:LINE},bubble:{alignSelf:'flex-start',backgroundColor:'#FCE1ED',borderRadius:17,padding:15,marginVertical:8,maxWidth:'82%'},profile:{backgroundColor:'#fff',borderRadius:24,padding:25,borderWidth:1,borderColor:LINE,marginBottom:20},demo:{textAlign:'center',fontSize:12,color:MUTED,marginTop:22,lineHeight:18},nav:{flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderTopColor:LINE,paddingHorizontal:4,paddingTop:9,paddingBottom:10},navItem:{flex:1,alignItems:'center',gap:4},navPill:{width:46,height:34,borderRadius:18,alignItems:'center',justifyContent:'center'},notice:{padding:10,backgroundColor:'#FCE1ED',alignItems:'center'}});
