import React, { useMemo, useRef, useState } from 'react';
import { Animated, Dimensions, Image, KeyboardAvoidingView, PanResponder, Platform, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFonts } from 'expo-font';
import { PlayfairDisplay_700Bold } from '@expo-google-fonts/playfair-display';
import { DMSans_400Regular, DMSans_500Medium, DMSans_600SemiBold, DMSans_700Bold } from '@expo-google-fonts/dm-sans';

const { width: SCREEN } = Dimensions.get('window');
const C = { background: '#F8F5F0', ink: '#252522', muted: '#75746F', olive: '#515F46', blush: '#F1DCD6', white: '#FFFFFF', line: '#E7E2DA', accent: '#DC6657' };
const F = { display: 'PlayfairDisplay_700Bold', regular: 'DMSans_400Regular', medium: 'DMSans_500Medium', semibold: 'DMSans_600SemiBold', bold: 'DMSans_700Bold' };
const CITIES = ['Warszawa', 'Kraków', 'Gdańsk', 'Wrocław', 'Poznań', 'Łódź'];
// Editorial placeholder photography, not actual members. Replace with consented user uploads before launch.
const PEOPLE = [
  { id: '1', name: 'Maja', age: 22, city: 'Warszawa', caption: 'Kawa, długie spacery i rozmowy do późna.', tags: ['Kawa', 'Spacery', 'Design'], image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900&q=85' },
  { id: '2', name: 'Ola', age: 23, city: 'Kraków', caption: 'Szukam dziewczyn do odkrywania nowych miejsc.', tags: ['Podróże', 'Kino', 'Kawa'], image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900&q=85' },
  { id: '3', name: 'Natalia', age: 21, city: 'Gdańsk', caption: 'Razem na pilates, potem na matchę?', tags: ['Pilates', 'Muzyka', 'Morze'], image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900&q=85' },
  { id: '4', name: 'Julia', age: 24, city: 'Warszawa', caption: 'Chodźmy na wystawę albo po prostu pogadać.', tags: ['Sztuka', 'Książki', 'Miasto'], image: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=900&q=85' },
];
const GROUPS = [
  { id: 'g1', title: 'Sunday coffee club', city: 'Warszawa', count: 'Kawa • rozmowy • nowe znajomości', symbol: '☕', color: '#E9D9C5' },
  { id: 'g2', title: 'Girls who move', city: 'Kraków', count: 'Pilates • spacery • aktywność', symbol: '↗', color: '#DCE4CF' },
  { id: 'g3', title: 'Book dates', city: 'Gdańsk', count: 'Książki • czytelnia • spotkania', symbol: '✳', color: '#EADFEA' },
];
const EVENTS = [
  { id: 'e1', day: '04', month: 'PAŹ', title: 'Kawa w nowym gronie', city: 'Warszawa', spot: 'Pomysł na spotkanie' },
  { id: 'e2', day: '08', month: 'PAŹ', title: 'Girls walk po mieście', city: 'Kraków', spot: 'Pomysł na spotkanie' },
  { id: 'e3', day: '12', month: 'PAŹ', title: 'Wieczór z książką', city: 'Gdańsk', spot: 'Pomysł na spotkanie' },
];
function Label({ children, style }) { return <Text style={[styles.eyebrow, style]}>{children}</Text>; }
function Button({ children, onPress, outline, style }) { return <TouchableOpacity activeOpacity={0.85} onPress={onPress} style={[styles.button, outline && styles.buttonOutline, style]}><Text style={[styles.buttonText, outline && styles.buttonOutlineText]}>{children}</Text></TouchableOpacity>; }
function Pill({ children, active, onPress }) { return <TouchableOpacity onPress={onPress} style={[styles.pill, active && styles.pillActive]}><Text style={[styles.pillText, active && styles.pillTextActive]}>{children}</Text></TouchableOpacity>; }

function SwipeCard({ profile, onSwipe, index }) {
  const position = useRef(new Animated.ValueXY()).current;
  const action = useRef(onSwipe);
  action.current = onSwipe;
  const pan = useRef(PanResponder.create({
    onMoveShouldSetPanResponder: (_, g) => Math.abs(g.dx) > 9 || Math.abs(g.dy) > 12,
    onPanResponderMove: (_, g) => position.setValue({ x: g.dx, y: g.dy * 0.15 }),
    onPanResponderRelease: (_, g) => {
      if (Math.abs(g.dx) > SCREEN * 0.22) {
        const direction = g.dx > 0 ? 'like' : 'pass';
        Animated.timing(position, { toValue: { x: (g.dx > 0 ? 1 : -1) * SCREEN * 1.2, y: g.dy * 0.2 }, duration: 200, useNativeDriver: true }).start(() => { position.setValue({ x: 0, y: 0 }); action.current(direction); });
      } else Animated.spring(position, { toValue: { x: 0, y: 0 }, friction: 6, useNativeDriver: true }).start();
    },
    onPanResponderTerminate: () => Animated.spring(position, { toValue: { x: 0, y: 0 }, useNativeDriver: true }).start(),
  })).current;
  const rotate = position.x.interpolate({ inputRange: [-SCREEN, 0, SCREEN], outputRange: ['-12deg', '0deg', '12deg'] });
  const yesOpacity = position.x.interpolate({ inputRange: [0, SCREEN * 0.3], outputRange: [0, 1], extrapolate: 'clamp' });
  const noOpacity = position.x.interpolate({ inputRange: [-SCREEN * 0.3, 0], outputRange: [1, 0], extrapolate: 'clamp' });
  return <Animated.View {...pan.panHandlers} style={[styles.swipeCard, { transform: [...position.getTranslateTransform(), { rotate }] }]}>
    <Image source={{ uri: profile.image }} style={styles.profilePhoto} resizeMode="cover" />
    <View style={styles.photoTint} />
    <View style={styles.photoTop}><View style={styles.onlineBadge}><Text style={styles.onlineText}>✦  PRZYKŁADOWY PROFIL</Text></View><Text style={styles.photoNumber}>0{index + 1} / 0{PEOPLE.length}</Text></View>
    <Animated.View style={[styles.stamp, styles.stampYes, { opacity: yesOpacity }]}><Text style={styles.stampText}>POZNAJMY SIĘ</Text></Animated.View>
    <Animated.View style={[styles.stamp, styles.stampNo, { opacity: noOpacity }]}><Text style={styles.stampText}>DALEJ</Text></Animated.View>
    <View style={styles.photoBottom}><Text style={styles.profileName}>{profile.name}, {profile.age}</Text><Text style={styles.profileCity}>⌖  {profile.city}</Text><Text style={styles.profileCaption}>{profile.caption}</Text><View style={styles.tags}>{profile.tags.map(tag => <Text key={tag} style={styles.tag}>{tag}</Text>)}</View></View>
  </Animated.View>;
}

export default function App() {
  const [fontsLoaded] = useFonts({ PlayfairDisplay_700Bold, DMSans_400Regular, DMSans_500Medium, DMSans_600SemiBold, DMSans_700Bold });
  const [name, setName] = useState('');
  const [homeCity, setHomeCity] = useState('Warszawa');
  const [city, setCity] = useState('Wszystkie');
  const [started, setStarted] = useState(false);
  const [tab, setTab] = useState('Odkrywaj');
  const [index, setIndex] = useState(0);
  const [liked, setLiked] = useState([]);
  const [joined, setJoined] = useState([]);
  const [saved, setSaved] = useState([]);
  const profiles = useMemo(() => PEOPLE.filter(p => city === 'Wszystkie' || p.city === city), [city]);
  const current = profiles[index];
  const swipe = (direction) => { if (direction === 'like' && current && !liked.includes(current.id)) setLiked(v => [...v, current.id]); setIndex(v => v + 1); };
  const chooseCity = value => { setCity(value); setIndex(0); };
  const flip = (id, setter) => setter(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  if (!fontsLoaded) return <SafeAreaView style={styles.safe}><Text style={styles.loading}>MyGirl</Text></SafeAreaView>;
  if (!started) return <SafeAreaView style={styles.safe}><StatusBar barStyle="dark-content" backgroundColor={C.background}/><KeyboardAvoidingView style={{flex: 1}} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.welcome} keyboardShouldPersistTaps="handled"><Label>NEW CONNECTIONS, REAL LIFE</Label><Text style={styles.brandHero}>mygirl<Text style={{color:C.accent}}>.</Text></Text><View style={styles.heroPicture}><Image source={{uri:PEOPLE[0].image}} style={styles.heroImage}/><View style={styles.heroSticker}><Text style={styles.heroStickerText}>your kind of people ↗</Text></View></View><Text style={styles.heroTitle}>Dobre znajomości zaczynają się tutaj.</Text><Text style={styles.description}>Poznawaj dziewczyny ze swojego miasta, znajduj wspólne pasje i wychodź razem w świat.</Text><Label>TWOJE IMIĘ</Label><TextInput value={name} onChangeText={setName} placeholder="Jak masz na imię?" placeholderTextColor={C.muted} style={styles.input} maxLength={30}/><Label>TWÓJ PUNKT NA MAPIE</Label><View style={styles.chips}>{CITIES.map(c => <Pill key={c} active={homeCity===c} onPress={() => setHomeCity(c)}>{c}</Pill>)}</View><Button onPress={() => {if(name.trim()){setStarted(true);chooseCity(homeCity);}}} style={{marginTop:20}}>Wejdź do MyGirl  ↗</Button><Text style={styles.demoNotice}>PROTOTYP • fikcyjne profile i spotkania • bez konta</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><StatusBar barStyle="dark-content" backgroundColor={C.background}/><View style={styles.top}><View><Text style={styles.topBrand}>mygirl<Text style={{color:C.accent}}>.</Text></Text><Label style={{marginTop:2}}>CZEŚĆ, {name.trim().toUpperCase()}</Label></View><TouchableOpacity onPress={() => setTab('Profil')} style={styles.topAvatar}><Text style={{fontSize:22}}>✳</Text></TouchableOpacity></View>
    {tab === 'Odkrywaj' ? <View style={styles.discover}><View style={styles.titleRow}><View><Label>DISCOVER / 01</Label><Text style={styles.pageTitle}>Twoje nowe<Text style={{fontStyle:'italic'}}> znajomości</Text></Text></View><Text style={styles.sparkle}>✳</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.chips,{paddingVertical:9}]} style={{flexGrow:0,marginBottom:9}}>{['Wszystkie',...CITIES].map(c=><Pill key={c} active={city===c} onPress={()=>chooseCity(c)}>{c}</Pill>)}</ScrollView>{current ? <View style={styles.cardArea}><SwipeCard key={current.id} profile={current} index={index} onSwipe={swipe}/></View> : <View style={styles.emptyCard}><Text style={styles.emptySymbol}>✳</Text><Text style={styles.emptyTitle}>Na dziś to wszystkie profile.</Text><Text style={styles.description}>Zmień miasto albo zobacz przykładowe profile jeszcze raz.</Text><Button outline onPress={()=>setIndex(0)}>Od początku ↻</Button></View>}
    <View style={styles.actions}><TouchableOpacity onPress={()=>current&&swipe('pass')} disabled={!current} style={[styles.actionCircle,{backgroundColor:C.white}]}><Text style={styles.passIcon}>×</Text></TouchableOpacity><View style={styles.actionHint}><Text style={styles.hintBold}>PRZESUŃ KARTĘ</Text><Text style={styles.hintSmall}>← dalej  •  poznajmy się →</Text></View><TouchableOpacity onPress={()=>current&&swipe('like')} disabled={!current} style={[styles.actionCircle,{backgroundColor:C.olive}]}><Text style={styles.likeIcon}>♡</Text></TouchableOpacity></View></View> : <ScrollView contentContainerStyle={styles.otherPage} keyboardShouldPersistTaps="handled">
    {tab==='Grupy' && <><Label>YOUR PEOPLE / 02</Label><Text style={styles.pageTitle}>Razem jest<Text style={{fontStyle:'italic'}}> ciekawiej.</Text></Text><Text style={styles.description}>Małe społeczności, wspólne zajawki i plany poza ekranem.</Text>{GROUPS.map(g=><View key={g.id} style={styles.listCard}><View style={[styles.groupIcon,{backgroundColor:g.color}]}><Text style={{fontSize:31,color:C.ink}}>{g.symbol}</Text></View><View style={{flex:1}}><Label>{g.city.toUpperCase()}</Label><Text style={styles.listTitle}>{g.title}</Text><Text style={styles.listDesc}>{g.count}</Text><TouchableOpacity onPress={()=>flip(g.id,setJoined)}><Text style={styles.listLink}>{joined.includes(g.id)?'Dołączono ✓':'Dołącz do grupy ↗'}</Text></TouchableOpacity></View></View>)}</>}
    {tab==='Spotkania' && <><Label>OFFLINE / 03</Label><Text style={styles.pageTitle}>Zobaczmy się<Text style={{fontStyle:'italic'}}> na żywo.</Text></Text><Text style={styles.description}>Inspiracje do wyjść. Terminy są przykładowe — nie są to potwierdzone wydarzenia.</Text>{EVENTS.map(e=><View key={e.id} style={styles.eventCard}><View style={styles.dateBlock}><Text style={styles.dateDay}>{e.day}</Text><Label>{e.month}</Label></View><View style={{flex:1}}><Label>{e.city.toUpperCase()} · DEMO</Label><Text style={styles.listTitle}>{e.title}</Text><Text style={styles.listDesc}>{e.spot}</Text></View><TouchableOpacity onPress={()=>flip(e.id,setSaved)}><Text style={styles.bookmark}>{saved.includes(e.id)?'♥':'♡'}</Text></TouchableOpacity></View>)}</>}
    {tab==='Profil' && <><Label>ABOUT YOU / 04</Label><Text style={styles.pageTitle}>Miło Cię<Text style={{fontStyle:'italic'}}> poznać.</Text></Text><View style={styles.profilePanel}><Text style={styles.profileMark}>✳</Text><Text style={styles.profilePanelName}>{name.trim()}</Text><Text style={styles.listDesc}>⌖ {homeCity}</Text><View style={styles.statRow}><View><Text style={styles.stat}>{liked.length}</Text><Label>POLUBIONE</Label></View><View><Text style={styles.stat}>{joined.length}</Text><Label>GRUPY</Label></View><View><Text style={styles.stat}>{saved.length}</Text><Label>ZAPISANE</Label></View></View></View><Text style={styles.description}>To wersja demonstracyjna. Wybory są lokalne i mogą zniknąć po ponownym uruchomieniu aplikacji. Zdjęcia są ilustracyjne.</Text><Button outline onPress={()=>setStarted(false)}>Edytuj mój profil ↗</Button></>}
  </ScrollView>}
  <View style={styles.nav}>{[['Odkrywaj','◈'],['Grupy','◎'],['Spotkania','▦'],['Profil','◉']].map(([t,ico])=><TouchableOpacity key={t} onPress={()=>setTab(t)} style={styles.navItem}><Text style={[styles.navSymbol,tab===t&&{color:C.olive}]}>{ico}</Text><Text style={[styles.navText,tab===t&&styles.navSelected]}>{t}</Text>{tab===t&&<View style={styles.activeLine}/>}</TouchableOpacity>)}</View>
  </SafeAreaView>;
}

const styles=StyleSheet.create({
  safe:{flex:1,backgroundColor:C.background}, loading:{fontSize:40,textAlign:'center',marginTop:100,color:C.olive},
  eyebrow:{fontFamily:F.bold,fontSize:9,letterSpacing:2,color:C.muted},brandHero:{fontFamily:F.display,fontSize:56,color:C.olive,marginTop:8,marginBottom:12},welcome:{padding:25,paddingTop:30,paddingBottom:42},heroPicture:{height:215,borderRadius:7,overflow:'hidden',marginBottom:22,backgroundColor:C.blush},heroImage:{width:'100%',height:'100%'},heroSticker:{position:'absolute',right:0,bottom:20,backgroundColor:C.olive,paddingHorizontal:16,paddingVertical:12,transform:[{rotate:'-4deg'}]},heroStickerText:{fontFamily:F.semibold,color:C.white,fontSize:12},heroTitle:{fontFamily:F.display,color:C.ink,fontSize:35,lineHeight:41,marginBottom:12},description:{fontFamily:F.regular,color:C.muted,fontSize:13,lineHeight:21,marginBottom:19},input:{borderBottomWidth:1,borderBottomColor:C.ink,paddingVertical:12,fontFamily:F.medium,fontSize:17,color:C.ink,marginBottom:23},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},pill:{borderWidth:1,borderColor:'#DCD9D1',paddingHorizontal:13,paddingVertical:9,borderRadius:30,backgroundColor:C.background},pillActive:{borderColor:C.olive,backgroundColor:C.olive},pillText:{color:C.ink,fontFamily:F.medium,fontSize:11},pillTextActive:{color:C.white},button:{backgroundColor:C.olive,padding:17,alignItems:'center',borderRadius:3},buttonOutline:{backgroundColor:'transparent',borderWidth:1,borderColor:C.olive},buttonText:{fontFamily:F.semibold,fontSize:13,color:C.white},buttonOutlineText:{color:C.olive},demoNotice:{fontFamily:F.medium,color:C.muted,textAlign:'center',fontSize:9,marginTop:18,letterSpacing:1},
  top:{height:74,borderBottomWidth:1,borderBottomColor:C.line,paddingHorizontal:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},topBrand:{fontFamily:F.display,color:C.olive,fontSize:29,lineHeight:32},topAvatar:{width:40,height:40,borderWidth:1,borderColor:C.line,borderRadius:20,alignItems:'center',justifyContent:'center'},discover:{flex:1,paddingHorizontal:20,paddingTop:20},titleRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},pageTitle:{fontFamily:F.display,color:C.ink,fontSize:29,lineHeight:37,marginTop:5,marginBottom:6},sparkle:{fontSize:29,color:C.olive},cardArea:{flex:1,minHeight:270,marginTop:5,marginHorizontal:3,marginBottom:10},swipeCard:{position:'absolute',width:'100%',height:'100%',borderRadius:7,overflow:'hidden',backgroundColor:'#C8B9AB',elevation:4,shadowColor:'#000',shadowOpacity:0.12,shadowRadius:12,shadowOffset:{width:0,height:6}},profilePhoto:{width:'100%',height:'100%'},photoTint:{position:'absolute',left:0,right:0,bottom:0,height:'54%',backgroundColor:'rgba(20,20,18,0.56)'},photoTop:{position:'absolute',top:15,left:15,right:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},onlineBadge:{backgroundColor:'rgba(255,255,255,0.94)',paddingHorizontal:10,paddingVertical:8,borderRadius:2},onlineText:{fontFamily:F.bold,color:C.ink,fontSize:8,letterSpacing:0.8},photoNumber:{fontFamily:F.bold,fontSize:10,color:C.white,letterSpacing:1},photoBottom:{position:'absolute',bottom:21,left:20,right:20},profileName:{fontFamily:F.display,fontSize:41,color:C.white,lineHeight:50},profileCity:{fontFamily:F.semibold,color:C.white,fontSize:12,marginTop:2},profileCaption:{fontFamily:F.regular,color:C.white,fontSize:14,marginTop:14,marginBottom:13,lineHeight:20},tags:{flexDirection:'row',gap:7,flexWrap:'wrap'},tag:{borderWidth:1,borderColor:'rgba(255,255,255,0.75)',color:C.white,paddingHorizontal:10,paddingVertical:6,fontFamily:F.semibold,fontSize:10,borderRadius:18},stamp:{position:'absolute',top:90,padding:10,borderWidth:3,borderRadius:4,transform:[{rotate:'-12deg'}]},stampYes:{left:23,borderColor:'#F0FFB0'},stampNo:{right:23,borderColor:'#FFF'},stampText:{fontFamily:F.bold,fontSize:17,color:C.white},actions:{height:90,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:11},actionCircle:{width:60,height:60,borderRadius:30,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:C.line},passIcon:{fontSize:41,color:C.accent,marginTop:-5,fontFamily:F.regular},likeIcon:{fontSize:40,color:C.white,marginTop:-3},actionHint:{alignItems:'center'},hintBold:{fontFamily:F.bold,color:C.ink,fontSize:9,letterSpacing:1.5},hintSmall:{fontFamily:F.regular,color:C.muted,fontSize:10,marginTop:6},emptyCard:{flex:1,backgroundColor:C.blush,justifyContent:'center',alignItems:'center',padding:30,borderRadius:6},emptySymbol:{fontSize:60,color:C.olive},emptyTitle:{fontFamily:F.display,fontSize:26,textAlign:'center',color:C.ink,marginBottom:12},
  nav:{height:71,flexDirection:'row',backgroundColor:C.background,borderTopWidth:1,borderTopColor:C.line,paddingHorizontal:8},navItem:{flex:1,alignItems:'center',paddingTop:12,position:'relative'},navSymbol:{fontSize:21,color:'#ADAAA2'},navText:{fontFamily:F.medium,fontSize:10,color:C.muted,marginTop:2},navSelected:{fontFamily:F.bold,color:C.olive},activeLine:{position:'absolute',top:0,width:26,height:2,backgroundColor:C.olive},otherPage:{padding:24,paddingBottom:45},listCard:{backgroundColor:C.white,flexDirection:'row',padding:14,marginTop:12,gap:14,borderRadius:4,borderWidth:1,borderColor:C.line},groupIcon:{width:78,height:105,alignItems:'center',justifyContent:'center'},listTitle:{fontFamily:F.display,fontSize:21,color:C.ink,marginTop:5},listDesc:{fontFamily:F.regular,fontSize:11,color:C.muted,marginTop:4,lineHeight:17},listLink:{fontFamily:F.bold,fontSize:11,color:C.olive,marginTop:13},eventCard:{flexDirection:'row',alignItems:'center',backgroundColor:C.white,padding:17,borderWidth:1,borderColor:C.line,marginTop:13,gap:15},dateBlock:{borderRightWidth:1,borderRightColor:C.line,paddingRight:15,alignItems:'center'},dateDay:{fontFamily:F.display,fontSize:34,color:C.olive},bookmark:{fontSize:26,color:C.accent},profilePanel:{backgroundColor:C.white,padding:27,marginTop:18,marginBottom:24,borderWidth:1,borderColor:C.line},profileMark:{fontSize:45,color:C.olive},profilePanelName:{fontFamily:F.display,fontSize:38,color:C.ink,marginTop:10},statRow:{flexDirection:'row',justifyContent:'space-between',marginTop:32,paddingTop:19,borderTopWidth:1,borderTopColor:C.line},stat:{fontFamily:F.display,fontSize:29,color:C.olive,marginBottom:5}
});
