import React,{useState} from 'react';
import {KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {cities,interests} from './data';
import {colors as c,space as sp,fonts as f} from './theme';
import {Button,Chip,Field,PageHeading,Typography} from './ui';
const steps=[['DZIEŃ DOBRY','Nowe znajomości.','Poznaj dziewczyny w swoim mieście.'],['TWÓJ CEL','Po co tu jesteś?','Wybierz to, na co masz ochotę.'],['LOKALNIE','Twoje miasto.','Zacznij od osób blisko Ciebie.'],['TWOJA ENERGIA','Co lubisz?','Wybierz kilka zainteresowań.'],['PRZEDSTAW SIĘ','Jak masz na imię?','Tylko tyle na początek.'],['TWOJE ZDJĘCIE','Pokaż siebie.','Zdjęcie dodasz po podłączeniu kont i bezpiecznego przesyłania.'],['BEZPIECZNIE','Twoje zasady.','Szanujemy Twoją prywatność.']];
export default function Onboarding({onComplete}){
const [step,setStep]=useState(0),[goal,setGoal]=useState('Przyjaźń'),[city,setCity]=useState('Warszawa'),[selected,setSelected]=useState([]),[name,setName]=useState(''),[consent,setConsent]=useState(false);
const ready=step===3?selected.length>0:step===4?name.trim().length>=2:step===6?consent:true;
const next=()=>{if(!ready)return;if(step===steps.length-1)onComplete({goal,city,interests:selected,name:name.trim(),photo:null,consent});else setStep(v=>v+1)};
return <KeyboardAvoidingView style={{flex:1,backgroundColor:c.canvas}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Wstecz" onPress={()=>setStep(v=>Math.max(0,v-1))} style={{width:40,paddingVertical:8}}>{step>0?<Ionicons name="arrow-back" size={24} color={c.ink}/>:null}</Pressable><Typography variant="caption" style={{color:c.muted}}>{step+1} / {steps.length}</Typography></View><View style={s.progress}><View style={[s.progressFill,{width:`${(step+1)/steps.length*100}%`}]}/></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><PageHeading kicker={steps[step][0]} title={steps[step][1]}/><Typography style={{color:c.muted,marginBottom:sp.xl,fontSize:17}}>{steps[step][2]}</Typography>
{step===0&&<View style={s.welcome}><Ionicons name="heart" size={84} color={c.pink}/><Typography variant="heading" style={{textAlign:'center',marginTop:20}}>MyGirl.</Typography><Typography style={{textAlign:'center',marginTop:8,color:c.muted}}>Przyjaźnie zaczynają się tutaj.</Typography></View>}
{step===1&&<View style={s.wrap}>{['Przyjaźń','Wspólne wyjścia','Nowe miasto','Grupy zainteresowań'].map(v=><Chip key={v} label={v} selected={goal===v} onPress={()=>setGoal(v)}/>)}</View>}
{step===2&&<View style={s.wrap}>{cities.map(v=><Chip key={v} label={v} selected={city===v} onPress={()=>setCity(v)}/>)}</View>}
{step===3&&<View style={s.wrap}>{interests.map(v=><Chip key={v} label={v} selected={selected.includes(v)} onPress={()=>setSelected(prev=>prev.includes(v)?prev.filter(i=>i!==v):[...prev,v])}/>)}</View>}
{step===4&&<Field label="Imię" value={name} onChangeText={setName} placeholder="Twoje imię"/>}
{step===5&&<View style={s.photo}><Ionicons name="camera-outline" size={38} color={c.pink}/><Typography style={{marginTop:12,color:c.muted}}>Dodawanie zdjęcia: w przygotowaniu</Typography></View>}
{step===6&&<><Typography style={{lineHeight:24}}>To prototyp. Profile, czaty i grupy są fikcyjne. Nie tworzymy jeszcze kont ani nie przechowujemy danych na serwerze.</Typography><Pressable accessibilityRole="checkbox" accessibilityState={{checked:consent}} onPress={()=>setConsent(v=>!v)} style={s.check}><Ionicons name={consent?'checkbox':'square-outline'} size={25} color={c.pink}/><Typography style={{flex:1}}>Rozumiem, że korzystam z demonstracji.</Typography></Pressable></>}
</ScrollView><View style={s.footer}><Button title={step===steps.length-1?'Otwórz MyGirl':'Dalej'} onPress={next} disabled={!ready} icon="arrow-forward"/></View></KeyboardAvoidingView>
}
const s=StyleSheet.create({top:{paddingHorizontal:sp.lg,paddingTop:sp.md,paddingBottom:sp.sm,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},progress:{height:3,backgroundColor:c.line},progressFill:{height:3,backgroundColor:c.pink},content:{flexGrow:1,padding:sp.lg,paddingTop:sp.xl},wrap:{flexDirection:'row',flexWrap:'wrap'},welcome:{flex:1,alignItems:'center',justifyContent:'center',paddingVertical:50},photo:{backgroundColor:c.blush,borderWidth:1,borderStyle:'dashed',borderColor:c.pink,borderRadius:24,padding:40,alignItems:'center'},check:{flexDirection:'row',gap:12,alignItems:'center',marginTop:32,padding:12},footer:{padding:sp.lg,borderTopWidth:1,borderColor:c.line,backgroundColor:c.white}});
