import React from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {colors as c,space as sp,radii as r,type as t,fonts as f} from './theme';
export function Typography({children,variant='body',style,...props}){const config={hero:[t.hero,f.display],heading:[t.heading,f.display],subtitle:[t.subtitle,f.semibold],body:[t.body,f.regular],caption:[t.caption,f.regular],eyebrow:[t.eyebrow,f.bold]}[variant];return <Text {...props} style={[{color:c.ink,fontFamily:config[1],fontSize:config[0]},style]}>{children}</Text>}
export function Button({title,onPress,secondary=false,disabled=false,icon,style}){return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&{opacity:.4},style]}>{icon&&<Ionicons name={icon} size={19} color={secondary?c.pink:c.white}/>}<Typography style={{color:secondary?c.pink:c.white,fontFamily:f.bold}}>{title}</Typography></Pressable>}
export function Chip({label,selected,onPress}){return <Pressable accessibilityRole="button" accessibilityState={{selected:!!selected}} onPress={onPress} style={[s.chip,selected&&{backgroundColor:c.pink,borderColor:c.pink}]}><Typography style={{fontSize:13,fontFamily:f.semibold,color:selected?c.white:c.ink}}>{label}</Typography></Pressable>}
export function Field({label,value,onChangeText,placeholder,autoCapitalize='sentences',keyboardType='default',multiline=false}){return <View style={{marginBottom:sp.base}}><Typography style={{fontFamily:f.semibold,marginBottom:sp.sm}}>{label}</Typography><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} autoCapitalize={autoCapitalize} keyboardType={keyboardType} multiline={multiline} style={[s.input,multiline&&{minHeight:88,textAlignVertical:'top'}]}/></View>}
export function PageHeading({kicker,title}){return <View style={{marginBottom:sp.lg}}><Typography variant="eyebrow" style={{color:c.pink,letterSpacing:1.6,marginBottom:sp.sm}}>{kicker}</Typography><Typography variant="hero">{title}</Typography></View>}
export function Surface({children,style}){return <View style={[s.surface,style]}>{children}</View>}
const s=StyleSheet.create({button:{minHeight:54,borderRadius:r.md,backgroundColor:c.pink,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:sp.sm,paddingHorizontal:sp.base},secondary:{backgroundColor:c.blush},chip:{paddingVertical:11,paddingHorizontal:16,borderRadius:r.pill,borderWidth:1,borderColor:c.line,backgroundColor:c.white,marginRight:sp.sm,marginBottom:sp.sm},input:{borderWidth:1,borderColor:c.line,backgroundColor:c.white,borderRadius:r.md,padding:sp.base,fontFamily:f.regular,fontSize:t.body,color:c.ink},surface:{backgroundColor:c.white,borderRadius:r.lg,padding:sp.base,borderWidth:1,borderColor:c.line,marginBottom:sp.md}});
